services:
  web:
    build:
      context: ./GeoDjangoDocker
      dockerfile: Dockerfile.prod
    command: gunicorn GeoDjangoDocker.wsgi:application --bind 0.0.0.0:8005
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8005
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgis/postgis:16-3.5
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - "5433:5432"
    networks:
      - app-network


  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "8005:8005"
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
