services:
  web:
    build:
      context: ./GeoDjangoDocker
      dockerfile: Dockerfile.prod
    command: gunicorn GeoDjangoDocker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgis/postgis:12-3.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "8005:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
